var sielTradeIn={};
(function(c){function z(a){var b=document.querySelectorAll(".siel-trade-in-popup-option");if("all"==a){h=0;c(".siel-trade-in-popup-option__type-guide").removeClass("show");c(".siel-trade-in-popup__disclaimer-wrap").removeClass("show");c("input[name$\x3d'-type']").prop("checked",!1);c("input[id\x3d'agree-checkbox-1']").prop("checked",!1);l=!1;for(a=0;a<b.length;a++)b[a].classList.remove("show");c(".siel-trade-in-popup__btn-order").addClass("cta--disabled");c(".pd-select-option.trade-in #pd-trade-in-0").removeAttr("data-total-price")}}function D(){var a=
"";if(0<d[k].variant.length){var b=d[k].variant.split(",");for(var f=0;f<b.length;f++)a+='\x3cli class\x3d"siel-trade-in-popup-option__item" role\x3d"listitem"\x3e\x3cdiv class\x3d"siel-trade-in-popup-selector"\x3e\x3cinput class\x3d"hidden" type\x3d"radio" name\x3d"size-type" id\x3d"size-type-'+f+'" value\x3d"'+b[f]+'"\x3e\x3clabel class\x3d"siel-trade-in-popup-selector__label" for\x3d"size-type-'+f+'"\x3e\x3cspan class\x3d"siel-trade-in-popup-selector__text-wrap"\x3e\x3cspan class\x3d"siel-trade-in-popup-selector__text"\x3e'+
b[f]+"\x3c/span\x3e\x3c/span\x3e\x3c/label\x3e\x3c/div\x3e\x3c/li\x3e";c(".siel-trade-in-popup-option__list--size-type").html(a);A(0)}}function B(){0==h?p=!0:1==h?c("input[name\x3d'size-type']").is(":checked")&&(p=!0):2==h&&c("input[name\x3d'brand-type']").is(":checked")&&(p=!0);if(p){var a=document.querySelectorAll(".siel-trade-in-popup-option");a[h].classList.add("show");h+=1;a.length-1==h&&(h=0,l=!0,c(".siel-trade-in-popup-option__type-guide").addClass("show"),c(".siel-trade-in-popup__disclaimer-wrap").addClass("show"));
p=!1}}function I(){var a="";document.cookie.match("xsdcxyn")&&(a=c.cookies.get("xsdcxyn",{domain:".samsung.com"}));var b=!1;"YG"===a&&(-1<"au,cn,nz,es,fr,it,nl,de,se,uk,sec,ru,be,be_fr,pl,dk,fi,no,ch,ch_fr,pt,cz,at,sk,my,id,ph,ro,lt,lv,ee,kz_kz,kz_ru,ua,hr,si".indexOf(w)?b=!0:b=!1);"true"===c("#isEppPage").val()&&(b=window.sg.epp.common.isLogged);a="";a=b?"current":"anonymous";b="";c("#shopParmLang").val()&&(b="?lang\x3d"+c("#shopParmLang").val());var d=w;"true"===c("#isEppPage").val()&&(d=c("#eppCompanyCode").val());
c.ajax({url:E+"/tokocommercewebservices/v2/"+d+"/users/"+a+"/carts"+b,type:"POST",dataType:"json",timeout:2E4,xhrFields:{withCredentials:!0},async:!0,success:function(a){a&&J()},error:function(a){}})}function J(){var a=c("#modelCode").val(),b=F+"/v1/exchange/api/gbr/trade-in/create-exchange";a={store_id:w,device_info:{state:{BROKEN:"NO"}},device_id:v.id,type:"TradeIn",sku:a,delayed_gratification:!1};"true"===c("#isEppPage").val()&&(a.store_id=c("#eppCompanyCode").val());c.ajax({headers:K,url:b,type:"POST",
dataType:"json",xhrFields:{withCredentials:!0},crossDomain:!0,async:!0,timeout:1E4,data:JSON.stringify(a),success:function(a){a&&(window.sg.components.dynamic.DetailAfterEvent.offerAndAddonsDiscount(a,"exchange"),window.sg.components.sielTradeInPopup.closePopup())},error:function(a){},complete:function(){}})}function L(){c.ajax({url:E+"/tokocommercewebservices/v2/uk/tnc?context\x3dSERVICE\x26value\x3dtradein_tc",type:"GET",dataType:"json",xhrFields:{withCredentials:!0},crossDomain:!0,async:!0,timeout:1E4,
data:JSON,success:function(a){a&&null!==a[0].content&&""!==a[0].content&&(a="\x3cp\x3e"+a[0].content+"\x3c/p\x3e",a+='\x3cp class\x3d"siel-trade-in-popup__agree-required-field"\x3e*Required field\x3c/p\x3e',c(".siel-trade-in-popup__agree-desc").html(a))},error:function(a){},complete:function(){}})}function A(a){setTimeout(function(){window.sg.components.sielTradeInPopup.resizePopup();window.sg.components.sielTradeInPopup.goScroll(a)},500)}var E=c("#storeDomain").val(),F=c("#gpvStoreDomain").val(),
w=c("#siteCode").val(),m=c("#priceCurrency").val(),n=c("#categoryTypeCode").val(),K={"Cache-Control":"no-cache","Content-Type":"application/json","Access-Control-Allow-Origin":"*"},u=c(".siel-trade-in-popup"),d={},p=!1,h=0,x="",q="",v=null,G={},l=!1,H="",k="TV";switch(n){case "08030000":k="Refrigerator";break;case "08010000":k="Laundry";break;case "08070000":k="Vacuum";break;case "07010000":k="Monitor"}c(document).on("click",".siel-trade-in-popup__close",function(){z("all")});c(document).on("click",
".siel-trade-in-popup__btn-cancel",function(){z("all")});c(document).on("click",".siel-trade-in-popup .siel-trade-in-popup-option__type-guide",function(){var a=c(".siel-trade-in-popup-option__type-guide-wrap");if(a.hasClass("show")){a=c(".siel-trade-in-popup .siel-trade-in-popup-option__type-guide-wrap");var b=c(".siel-trade-in-popup #guide-btn");a.removeClass("show");a.addClass("hide");b.attr("xlink:href","#open-down-regular");b.attr("href","#open-down-regular")}else a.hasClass("hide")&&(a=c(".siel-trade-in-popup .siel-trade-in-popup-option__type-guide-wrap"),
b=c(".siel-trade-in-popup #guide-btn"),a.removeClass("hide"),a.addClass("show"),b.attr("xlink:href","#close-up-regular"),b.attr("href","#close-up-regular"))});c(document).on("click","input[name$\x3d'-type']",function(){var a=c(this).attr("name");c("input[name\x3d'"+a+"']").prop("checked",!1);c(this).prop("checked",!0);a=document.querySelectorAll(".siel-trade-in-popup-option");if(1<h&&c(a).hasClass("show"))for(var b=h=2;b<a.length;b++)a[b].classList.remove("show");else if(l&&c(a).hasClass("show")){l=
!1;for(b=h=2;b<a.length;b++)a[b].classList.remove("show");c(".siel-trade-in-popup__disclaimer-wrap").removeClass("show")}if("size-type"==c(this).attr("name")&&(l=!1,c(this).prop("checked")&&(x=c(this).val()),a=q="",0<d[k].brand.length)){b=d[k].brand.split(",");for(var f=0;f<b.length;f++)a+='\x3cli class\x3d"siel-trade-in-popup-option__item" role\x3d"listitem"\x3e\x3cdiv class\x3d"siel-trade-in-popup-selector"\x3e\x3cinput class\x3d"hidden" type\x3d"radio" name\x3d"brand-type" id\x3d"brand-type-'+
f+'" value\x3d"'+b[f]+'"\x3e\x3clabel class\x3d"siel-trade-in-popup-selector__label" for\x3d"brand-type-'+f+'"\x3e\x3cspan class\x3d"siel-trade-in-popup-selector__text-wrap"\x3e\x3cspan class\x3d"siel-trade-in-popup-selector__text"\x3e'+b[f]+"\x3c/span\x3e\x3c/span\x3e\x3c/label\x3e\x3c/div\x3e\x3c/li\x3e";c(".siel-trade-in-popup-option__list--brand-type").html(a);A(1)}if("brand-type"==c(this).attr("name")){a=[];c(this).prop("checked")&&(q=c(this).val());l=x?!0:!1;b=d[k][x];f=d[k][q];for(var C=0;C<
b.length;C++)for(var y=0;y<f.length;y++)b[C]==f[y]&&(G=f[y],a.push(G));v=a[0];A(2);if(l){a="Other"!==q?'\x3cspan style\x3d"color:#0381fe;"\x3e'+q+" "+v.name+"\x3c/span\x3e":'\x3cspan style\x3d"color:#0381fe;"\x3e '+v.name+"\x3c/span\x3e";c(".siel-trade-in-popup-offer__desc-product-info-text").html(a);a=v.estimated_discount.total.amount;c(".pd-select-option.trade-in #pd-trade-in-0").attr("data-total-price",a);b='\x3cstrong\x3eGet \x3cspan style\x3d"color:#0381fe;"\x3e'+currencyComma(a,m)+"\x3c/span\x3e off your order instantly for recycling your TV\x3c/strong\x3e";
if("08030000"===n||"08010000"===n||"08070000"===n||"07010000"===n)switch(n){case "08030000":b='\x3cstrong\x3eGet \x3cspan style\x3d"color:#0381fe;"\x3e'+currencyComma(a,m)+"\x3c/span\x3e for recycling your refrigerator\x3c/strong\x3e";break;case "08010000":b='\x3cstrong\x3eGet \x3cspan style\x3d"color:#0381fe;"\x3e'+currencyComma(a,m)+"\x3c/span\x3e for recycling your laundry device\x3c/strong\x3e";break;case "08070000":b='\x3cstrong\x3eGet \x3cspan style\x3d"color:#0381fe;"\x3e'+currencyComma(a,
m)+"\x3c/span\x3e for recycling your vacuum\x3c/strong\x3e";break;case "07010000":b='\x3cstrong\x3eGet an instant discount of \x3cspan style\x3d"color:#0381fe;"\x3e'+currencyComma(a,m)+"\x3c/span\x3e for recycling your monitor\x3c/strong\x3e"}c(".siel-trade-in-popup-offer__desc-value-provided").html(b)}}a=!1;c("input[id\x3d'agree-checkbox-1']").is(":checked")&&(a=!0);q&&x&&a?c(".siel-trade-in-popup__btn-order").removeClass("cta--disabled"):c(".siel-trade-in-popup__btn-order").addClass("cta--disabled");
B()});c(document).on("click",".checkbox-v2__input",function(){c("input[id\x3d'agree-checkbox-1']").is(":checked")?c(".siel-trade-in-popup__btn-order").removeClass("cta--disabled"):c(".siel-trade-in-popup__btn-order").addClass("cta--disabled")});c(document).on("click",".siel-trade-in-popup__btn-wrap .cta--contained",function(){I()});sielTradeIn={initializeStep:z,callSkuDevicesAjax:function(a){var b=c("#modelCode").val(),f=w;"true"===c("#isEppPage").val()&&(f=c("#eppCompanyCode").val());H===b&&Object.keys(d).length?
(B(),D()):(b=F+"/v1/exchange/api/gbr/trade-in/sku-devices/"+f+"/"+b,f="true"===c("#isEppPage").val()?{withCredentials:!0}:{},c.ajax({url:b,type:"GET",cache:!0,xhrFields:f,crossDomain:!0,dataType:"json",timeout:2E4,success:function(b,f,g){if(200===g.status&&b&&0<b.length){B();d={category:""};f=0;g=[];for(var e=0;e<b.length;e++)g.push(b[e]);if(0<g.length){for(b=0;b<g.length;b++){e=g[b].category;var h=g[b].series,k=g[b].memory,l=g[b].brand,q=g[b].estimated_discount;null!=g[b].category&&(null==d[e]&&
(d[e]=[]),""===d.category?0>d.category.indexOf(e)&&(d.category=e):0>d.category.indexOf(e)&&(d.category=d.category+","+e),null==d[e][h]&&(d[e][h]=[]),d[e][h].push(g[b]),null==d[e].series?d[e].series=h:0>d[e].series.indexOf(h)&&(d[e].series=d[e].series+","+h),null==d[e][k]&&(d[e][k]=[]),d[e][k].push(g[b]),null==d[e].variant?d[e].variant=k:0>d[e].variant.indexOf(k)&&(d[e].variant=d[e].variant+","+k),null==d[e][l]&&(d[e][l]=[]),d[e][l].push(g[b]),null==d[e].brand?d[e].brand=l:0>d[e].brand.indexOf(l)&&
(d[e].brand=d[e].brand+","+l),q&&f<g[b].estimated_discount.total.amount&&(f=g[b].estimated_discount.total.amount))}b=f;if(f=c(".pd-buying-tool__option .pd-select-option.trade-in")){H=c("#modelCode").val();a.ceMaxDiscount=b;g=Granite.I18n.get("Want up to {0} off? Recycle your old TV for an instant discount.",currencyComma(b,m));if("08030000"===n||"08010000"===n||"08070000"===n||"07010000"===n){switch(n){case "08030000":g=Granite.I18n.get("Want up to {0} off? Recycle your old fridge or freezer for an instant discount.",
currencyComma(b,m));var r="Fridge type";var p="Trade up and recycle your refrigerator";var t="appliance";break;case "08010000":g=Granite.I18n.get("Want up to {0} off? Recycle your old appliance for an instant discount.",currencyComma(b,m));r="Type of appliance";p="Trade up and recycle your appliance";t="appliance";break;case "08070000":g=Granite.I18n.get("Want up to {0} off? Recycle your old appliance for an instant discount.",currencyComma(b,m));r="Type of Vacuum Cleaner";p="Trade up and recycle your vacuum";
t="appliance";break;case "07010000":g=Granite.I18n.get("Want up to {0} off? Recycle your old monitor for an instant discount.",currencyComma(b,m)),r="Monitor type",p="Trade up and recycle your monitor",t="monitor"}"appliance"===t?(e="Recycle your appliance to trade up",disclaimer=Granite.I18n.get("uk-ce:da-disclaimer")):(e="Recycle your monitor to trade up",disclaimer=Granite.I18n.get("uk-ce:da-monitor-disclaimer"));u.find(".siel-trade-in-popup__title").html(e);u.find(".siel-select-size h3").html(r);
u.find(".siel-offer").html(p);u.find(".siel-trade-in-popup-option__type-guide-desc").eq(0).html(Granite.I18n.get("uk-ce:da-{0}-img-desc-1",t));u.find(".siel-trade-in-popup-option__type-guide-desc").eq(1).html(Granite.I18n.get("uk-ce:da-{0}-img-desc-2",t));u.find(".siel-trade-in-popup-option__type-guide-desc").eq(2).html(Granite.I18n.get("uk-ce:da-{0}-img-desc-3",t))}r=Granite.I18n.get("Save up to")+" "+currencyComma(b,m);a.ceHeadlineText=g;a.ceSubText=r;f.find(".pd-select-option__headline").html(g);
f.find(".pd-option-selector__sub-text:first").html(r)}}D();window.sg.components.dynamic.DetailAfterEvent.drawTradeInWithPopup({maxDiscount:0,directOutLink:!1,flag:!0})}},error:function(){},complete:function(){L()}}))}}})(window.jQuery);